language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install flake8
script:
  coverage run --source=apache_log_parser setup.py test && flake8
after_success:
  coveralls
